# Generated by Django 4.2.1 on 2023-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.TextField()),
                ("amount", models.IntegerField()),
                ("category", models.CharField(max_length=255)),
                ("store", models.CharField(max_length=255)),
                ("score", models.FloatField()),
            ],
        ),
    ]
